#!/usr/bin/env python3
"""
Accuracy validation script for Triton deployment.

Compares Triton inference outputs against vLLM baseline to ensure
the deployment doesn't introduce accuracy drift.

Usage:
    # First, ensure you have baseline outputs from vLLM
    # (generated by scripts/establish_baseline.py or scripts/evaluate_vllm_accuracy.py)

    # Then validate Triton outputs
    python validate_triton_accuracy.py \
        --triton-url http://localhost:8000 \
        --model qwen2vl_nutrition_gptq_int4 \
        --baseline /ssd1/zhuoyuan/vlm_outputs/quantization_experiments/bf16_baseline_outputs.json \
        --output triton_validation_results.json
"""

import argparse
import base64
import json
import re
import sys
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Optional
import io

import requests
from PIL import Image

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from src.models.inference import parse_qwen_bbox_output
except ImportError:
    # Fallback parser if import fails
    def parse_qwen_bbox_output(text: str) -> Optional[tuple]:
        """Parse bounding box from model output."""
        pattern = r'<\|box_start\|>\s*\((\d+),\s*(\d+)\)\s*,\s*\((\d+),\s*(\d+)\)\s*<\|box_end\|>'
        match = re.search(pattern, text)
        if match:
            x1, y1, x2, y2 = map(int, match.groups())
            return (x1 / 1000, y1 / 1000, x2 / 1000, y2 / 1000)
        return None


@dataclass
class ValidationResult:
    """Single validation result."""
    sample_id: int
    triton_output: str
    baseline_output: str
    triton_bbox: Optional[tuple]
    baseline_bbox: Optional[tuple]
    exact_match: bool
    bbox_match: bool
    iou: float
    latency_ms: float


@dataclass
class ValidationSummary:
    """Overall validation summary."""
    model_name: str
    num_samples: int
    exact_match_rate: float
    bbox_match_rate: float
    mean_iou: float
    median_iou: float
    iou_above_50: float
    iou_above_70: float
    avg_latency_ms: float
    all_match: bool


def calculate_iou(box1: Optional[tuple], box2: Optional[tuple]) -> float:
    """Calculate IoU between two bounding boxes."""
    if box1 is None or box2 is None:
        return 0.0

    x1_1, y1_1, x2_1, y2_1 = box1
    x1_2, y1_2, x2_2, y2_2 = box2

    # Intersection
    xi1 = max(x1_1, x1_2)
    yi1 = max(y1_1, y1_2)
    xi2 = min(x2_1, x2_2)
    yi2 = min(y2_1, y2_2)

    if xi2 <= xi1 or yi2 <= yi1:
        return 0.0

    intersection = (xi2 - xi1) * (yi2 - yi1)

    # Union
    area1 = (x2_1 - x1_1) * (y2_1 - y1_1)
    area2 = (x2_2 - x1_2) * (y2_2 - y1_2)
    union = area1 + area2 - intersection

    return intersection / union if union > 0 else 0.0


def load_image_as_base64(image_path: str = None, image_pil: Image.Image = None) -> str:
    """Convert image to base64 string."""
    if image_pil is None and image_path:
        image_pil = Image.open(image_path)

    buffer = io.BytesIO()
    image_pil.save(buffer, format="JPEG")
    return base64.b64encode(buffer.getvalue()).decode("utf-8")


def send_triton_request(
    url: str,
    model_name: str,
    prompt: str,
    image_b64: str,
    timeout: int = 60
) -> tuple[Optional[str], float]:
    """Send inference request to Triton and return output + latency."""
    payload = {
        "inputs": [
            {
                "name": "text_input",
                "shape": [1],
                "datatype": "BYTES",
                "data": [prompt]
            },
            {
                "name": "image",
                "shape": [1],
                "datatype": "BYTES",
                "data": [image_b64]
            },
            {
                "name": "sampling_parameters",
                "shape": [1],
                "datatype": "BYTES",
                "data": ['{"temperature": 0, "max_tokens": 100}']
            },
            {
                "name": "stream",
                "shape": [1],
                "datatype": "BOOL",
                "data": [False]
            }
        ]
    }

    endpoint = f"{url}/v2/models/{model_name}/infer"

    start_time = time.perf_counter()
    try:
        response = requests.post(endpoint, json=payload, timeout=timeout)
        latency_ms = (time.perf_counter() - start_time) * 1000

        if response.status_code == 200:
            result = response.json()
            outputs = result.get("outputs", [])
            for output in outputs:
                if output.get("name") == "text_output":
                    text = output.get("data", [None])[0]
                    return text, latency_ms
        else:
            print(f"Error: HTTP {response.status_code}")
            return None, latency_ms
    except Exception as e:
        latency_ms = (time.perf_counter() - start_time) * 1000
        print(f"Request failed: {e}")
        return None, latency_ms

    return None, latency_ms


def load_baseline_outputs(baseline_path: str) -> dict:
    """Load baseline outputs from JSON file."""
    with open(baseline_path, "r") as f:
        data = json.load(f)

    # Handle different baseline formats
    if "results" in data:
        return {r["sample_id"]: r for r in data["results"]}
    elif isinstance(data, list):
        return {i: {"output": item.get("output", item.get("raw_output", ""))} for i, item in enumerate(data)}
    else:
        return data


def main():
    parser = argparse.ArgumentParser(description="Validate Triton accuracy against baseline")
    parser.add_argument("--triton-url", type=str, default="http://localhost:8000",
                        help="Triton server URL")
    parser.add_argument("--model", type=str, default="qwen2vl_nutrition_gptq_int4",
                        help="Model name on Triton")
    parser.add_argument("--baseline", type=str, required=True,
                        help="Path to baseline outputs JSON")
    parser.add_argument("--num-samples", type=int, default=None,
                        help="Number of samples to validate (default: all)")
    parser.add_argument("--output", type=str, default=None,
                        help="Output JSON file path")
    parser.add_argument("--prompt", type=str,
                        default="Detect the nutrition facts table in this image and return the bounding box coordinates.",
                        help="Prompt to use for inference")

    args = parser.parse_args()

    # Load baseline
    print(f"Loading baseline from: {args.baseline}")
    baseline_data = load_baseline_outputs(args.baseline)
    print(f"Loaded {len(baseline_data)} baseline samples")

    # Load dataset for images
    print("Loading dataset...")
    try:
        from datasets import load_dataset
        dataset = load_dataset(
            "zhuoyuaneh/nutrition_facts",
            split="validation",
            trust_remote_code=True
        )
    except Exception as e:
        print(f"Failed to load dataset: {e}")
        return

    # Determine number of samples
    num_samples = args.num_samples or min(len(baseline_data), len(dataset))
    print(f"Validating {num_samples} samples...")

    # Check Triton health
    try:
        health_response = requests.get(f"{args.triton_url}/v2/health/live", timeout=5)
        if health_response.status_code != 200:
            print(f"Triton server not healthy: {health_response.status_code}")
            return
        print("Triton server is healthy")
    except Exception as e:
        print(f"Cannot connect to Triton: {e}")
        return

    # Run validation
    results = []
    ious = []

    for i in range(num_samples):
        print(f"\rProcessing sample {i + 1}/{num_samples}...", end="", flush=True)

        # Get image
        image = dataset[i]["image"]
        image_b64 = load_image_as_base64(image_pil=image)

        # Get Triton output
        triton_output, latency_ms = send_triton_request(
            args.triton_url, args.model, args.prompt, image_b64
        )

        # Get baseline output
        baseline_entry = baseline_data.get(i, baseline_data.get(str(i), {}))
        baseline_output = baseline_entry.get("output", baseline_entry.get("raw_output", ""))

        # Parse bboxes
        triton_bbox = parse_qwen_bbox_output(triton_output) if triton_output else None
        baseline_bbox = parse_qwen_bbox_output(baseline_output) if baseline_output else None

        # Calculate metrics
        exact_match = triton_output == baseline_output
        bbox_match = triton_bbox == baseline_bbox
        iou = calculate_iou(triton_bbox, baseline_bbox)
        ious.append(iou)

        results.append(ValidationResult(
            sample_id=i,
            triton_output=triton_output or "",
            baseline_output=baseline_output,
            triton_bbox=triton_bbox,
            baseline_bbox=baseline_bbox,
            exact_match=exact_match,
            bbox_match=bbox_match,
            iou=iou,
            latency_ms=latency_ms
        ))

    print()  # New line after progress

    # Calculate summary
    exact_matches = sum(1 for r in results if r.exact_match)
    bbox_matches = sum(1 for r in results if r.bbox_match)
    sorted_ious = sorted(ious)

    summary = ValidationSummary(
        model_name=args.model,
        num_samples=num_samples,
        exact_match_rate=exact_matches / num_samples,
        bbox_match_rate=bbox_matches / num_samples,
        mean_iou=sum(ious) / len(ious) if ious else 0,
        median_iou=sorted_ious[len(sorted_ious) // 2] if sorted_ious else 0,
        iou_above_50=sum(1 for iou in ious if iou > 0.5) / len(ious) if ious else 0,
        iou_above_70=sum(1 for iou in ious if iou > 0.7) / len(ious) if ious else 0,
        avg_latency_ms=sum(r.latency_ms for r in results) / len(results) if results else 0,
        all_match=exact_matches == num_samples
    )

    # Print summary
    print("\n" + "=" * 60)
    print("VALIDATION RESULTS")
    print("=" * 60)
    print(f"\nModel: {summary.model_name}")
    print(f"Samples: {summary.num_samples}")
    print(f"\n[Match Rates]")
    print(f"  Exact match:  {summary.exact_match_rate:.1%} ({exact_matches}/{num_samples})")
    print(f"  Bbox match:   {summary.bbox_match_rate:.1%} ({bbox_matches}/{num_samples})")
    print(f"\n[IoU Metrics]")
    print(f"  Mean IoU:     {summary.mean_iou:.4f}")
    print(f"  Median IoU:   {summary.median_iou:.4f}")
    print(f"  IoU > 0.5:    {summary.iou_above_50:.1%}")
    print(f"  IoU > 0.7:    {summary.iou_above_70:.1%}")
    print(f"\n[Latency]")
    print(f"  Avg latency:  {summary.avg_latency_ms:.1f} ms")
    print(f"\n[Validation Status]")
    if summary.all_match:
        print("  ✓ ALL OUTPUTS MATCH BASELINE")
    else:
        print(f"  ⚠ {num_samples - exact_matches} outputs differ from baseline")
    print("=" * 60 + "\n")

    # Show mismatches
    mismatches = [r for r in results if not r.exact_match]
    if mismatches and len(mismatches) <= 10:
        print("Mismatched samples:")
        for r in mismatches[:5]:
            print(f"  Sample {r.sample_id}:")
            print(f"    Triton:   {r.triton_output[:80]}...")
            print(f"    Baseline: {r.baseline_output[:80]}...")
            print(f"    IoU: {r.iou:.4f}")
            print()

    # Save results
    if args.output:
        output_data = {
            "summary": asdict(summary),
            "results": [
                {
                    "sample_id": r.sample_id,
                    "exact_match": r.exact_match,
                    "bbox_match": r.bbox_match,
                    "iou": r.iou,
                    "latency_ms": r.latency_ms,
                    "triton_bbox": r.triton_bbox,
                    "baseline_bbox": r.baseline_bbox,
                }
                for r in results
            ]
        }

        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            json.dump(output_data, f, indent=2)
        print(f"Results saved to: {args.output}")


if __name__ == "__main__":
    main()
